### PR TITLE
Connect List Matakuliah Page with API

### LINKED ISSUE #19: Connect List Matakuliah Page with API
Mengkoneksikan page dengan API server dengan library [Axios](https://github.com/axios/axios)
sesuaikan dengan API yang udah dibuat di [documentation](https://documenter.getpostman.com/view/8289361/TVRn47ch) bagian subject

### PR DESCRIPTION
**Pull request by ryuuzake**
Fixes #19

### CODE REVIEW

**Comment by ryuuzake** [comment]
TODO
---
- [ ] Check if subjects correct with Authorization
- [ ] Change Loading Center Page
- [ ] Change Error Page

**Comment by ryuuzake** [comment]
sing List Mata Kuliah iki tak ganti maneh ta karo Error Page sing nyar? @rizabach29

**Comment by rizabach29** [comment]
Error page sing tak gawe error 404 tok

**Comment by ryuuzake** [comment]
iyo gak opo tak kei error 404 ngono ae lek error, yo opo?

**Pull request merged**
